// <auto-generated />
namespace WebTruyen.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class adddatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adddatabase));
        
        string IMigrationMetadata.Id
        {
            get { return "201903240730141_add-database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
